//
//  Constants.swift
//  MyTravels
//
//  Created by Frank Martin Jr on 12/9/18.
//  Copyright © 2018 Frank Martin Jr. All rights reserved.
//

import Foundation
import FirebaseDatabase
import FirebaseStorage

class Constants {
    
    // MARK: - Notifications
    
    static public let sharedTripsReceivedNotif = Notification.Name("sharedTripsReceived")
    static public let profilePictureUpdatedNotif = Notification.Name("profilePictureUpdatedNotification")
    static public let refreshSharedTripsListNotif = Notification.Name("refreshSharedTripsListNotif")
    static public let userLoggedInNotif = Notification.Name("userLoggedInNotif")
    static public let viewWillAppearForVC = Notification.Name("userLoggedInNotif")
    
    // MARK: - Error messages
    
    static public let somethingWentWrong = "Something went wrong. Please try again."

    
    // MARK: - Firebase references
    
    static public let databaseRef = Database.database().reference()
    static public let storageRef = Storage.storage().reference()
    
    // MARK: - Firebase child names
    
    static public let trip = "Trip"
    static public let crumb = "Crumb"
    static public let photo = "Photo"
    static public let user = "User"
    static public let places = "places"
    static public let photoID = "photoID"
    static public let photoURLs = "photoURLs"
    static public let sharedTripIDs = "sharedTripIDs"
    static public let participantTripIDs = "tripsFollowingUIDs"
    
    // MARK: - Legal Info
    
    static let privacyPolicy =
    
    """
Effective date: May 28, 2019

Breadcrumbz ("us", "we", or "our") operates the Breadcrumbz mobile application
(hereinafter referred to as the "Service").

This page informs you of our policies regarding the collection, use and
disclosure of personal data when you use our Service and the choices you have
associated with that data.

We use your data to provide and improve the Service. By using the Service, you
agree to the collection and use of information in accordance with this policy.
Unless otherwise defined in this Privacy Policy, the terms used in this
Privacy Policy have the same meanings as in our Terms and Conditions.

Definitions
-----------

* Service

Service is the Breadcrumbz mobile application operated by Breadcrumbz

* Personal Data

Personal Data means data about a living individual who can be identified
from those data (or from those and other information either in our
possession or likely to come into our possession).

* Usage Data

Usage Data is data collected automatically either generated by the use of
the Service or from the Service infrastructure itself (for example, the
duration of a page visit).

* Cookies

Cookies are small files stored on your device (computer or mobile device).

Information Collection and Use
------------------------------

We collect several different types of information for various purposes to
provide and improve our Service to you.

Types of Data Collected
~~~~~~~~~~~~~~~~~~~~~~~

Personal Data
*************

While using our Service, we may ask you to provide us with certain personally
identifiable information that can be used to contact or identify you
("Personal Data"). Personally identifiable information may include, but is not
limited to:

* Email address
* Cookies and Usage Data

Usage Data
**********

When you access the Service with a mobile device, we may collect certain
information automatically, including, but not limited to, the type of mobile
device you use, your mobile device unique ID, the IP address of your mobile
device, your mobile operating system, the type of mobile Internet browser you
use, unique device identifiers and other diagnostic data ("Usage Data").

Location Data
*************

We may use and store information about your location if you give us permission
to do so ("Location Data"). We use this data to provide features of our
Service, to improve and customise our Service.

You can enable or disable location services when you use our Service at any
time by way of your device settings.

Tracking &amp; Cookies Data
************

We use cookies and similar tracking technologies to track the activity on our
Service and we hold certain information.

Cookies are files with a small amount of data which may include an anonymous
unique identifier. Cookies are sent to your browser from a website and stored
on your device. Other tracking technologies are also used such as beacons,
tags and scripts to collect and track information and to improve and analyse
our Service.

You can instruct your browser to refuse all cookies or to indicate when a
cookie is being sent. However, if you do not accept cookies, you may not be
able to use some portions of our Service.

Examples of Cookies we use:

* Session Cookies. We use Session Cookies to operate our Service.
* Preference Cookies. We use Preference Cookies to remember your preferences
and various settings.
* Security Cookies. We use Security Cookies for security purposes.

Use of Data
-----------

Breadcrumbz uses the collected data for various purposes:

* To provide and maintain our Service
* To notify you about changes to our Service
* To allow you to participate in interactive features of our Service when
you choose to do so
* To provide customer support
* To gather analysis or valuable information so that we can improve our
Service
* To monitor the usage of our Service
* To detect, prevent and address technical issues

Transfer of Data
----------------

Your information, including Personal Data, may be transferred to - and
maintained on - computers located outside of your state, province, country or
other governmental jurisdiction where the data protection laws may differ from
those of your jurisdiction.

If you are located outside United States and choose to provide information to
us, please note that we transfer the data, including Personal Data, to United
States and process it there.

Your consent to this Privacy Policy followed by your submission of such
information represents your agreement to that transfer.

Breadcrumbz will take all the steps reasonably necessary to ensure that your
data is treated securely and in accordance with this Privacy Policy and no
transfer of your Personal Data will take place to an organisation or a country
unless there are adequate controls in place including the security of your
data and other personal information.

Disclosure of Data
------------------

Legal Requirements
~~~~~~~~~~~~~~~~~~

Breadcrumbz may disclose your Personal Data in the good faith belief that such
action is necessary to:

* To comply with a legal obligation
* To protect and defend the rights or property of Breadcrumbz
* To prevent or investigate possible wrongdoing in connection with the
Service
* To protect the personal safety of users of the Service or the public
* To protect against legal liability

Security of Data
----------------

The security of your data is important to us but remember that no method of
transmission over the Internet or method of electronic storage is 100% secure.
While we strive to use commercially acceptable means to protect your Personal
Data, we cannot guarantee its absolute security.

Service Providers
-----------------

We may employ third party companies and individuals to facilitate our Service
("Service Providers"), provide the Service on our behalf, perform Service-
related services or assist us in analysing how our Service is used.

These third parties have access to your Personal Data only to perform these
tasks on our behalf and are obligated not to disclose or use it for any other
purpose.

Links to Other Sites
--------------------

Our Service may contain links to other sites that are not operated by us. If
you click a third party link, you will be directed to that third party's site.
We strongly advise you to review the Privacy Policy of every site you visit.

We have no control over and assume no responsibility for the content, privacy
policies or practices of any third party sites or services.

Children's Privacy
------------------

Our Service does not address anyone under the age of 18 ("Children").

We do not knowingly collect personally identifiable information from anyone
under the age of 18. If you are a parent or guardian and you are aware that
your Child has provided us with Personal Data, please contact us. If we become
aware that we have collected Personal Data from children without verification
of parental consent, we take steps to remove that information from our
servers.

Changes to This Privacy Policy
------------------------------

We may update our Privacy Policy from time to time. We will notify you of any
changes by posting the new Privacy Policy on this page.

We will let you know via email and/or a prominent notice on our Service, prior
to the change becoming effective and update the "effective date" at the top of
this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes.
Changes to this Privacy Policy are effective when they are posted on this
page.

Contact Us
----------

If you have any questions about this Privacy Policy, please contact us:

* By email: fmartin0212@gmail.com

"""
    
    static public let termsAndConditions =
"""
    Last updated: May 28, 2019

    Please read these Terms and Conditions ("Terms", "Terms and Conditions")
    carefully before using the Breadcrumbz mobile application (the "Service")
    operated by Breadcrumbz ("us", "we", or "our").

    Your access to and use of the Service is conditioned upon your acceptance of
    and compliance with these Terms. These Terms apply to all visitors, users and
    others who wish to access or use the Service.

    By accessing or using the Service you agree to be bound by these Terms. If you
    disagree with any part of the terms then you do not have permission to access
    the Service.

    Communications
    --------------

    By creating an Account on our service, you agree to subscribe to newsletters,
    marketing or promotional materials and other information we may send. However,
    you may opt out of receiving any, or all, of these communications from us by
    following the unsubscribe link or instructions provided in any email we send.

    Content
    -------

    Our Service allows you to post, link, store, share and otherwise make
    available certain information, text, graphics, videos, or other material
    ("Content"). You are responsible for the Content that you post on or through
    the Service, including its legality, reliability, and appropriateness.

    By posting Content on or through the Service, You represent and warrant that:
    (i) the Content is yours (you own it) and/or you have the right to use it and
    the right to grant us the rights and license as provided in these Terms, and
    (ii) that the posting of your Content on or through the Service does not
    violate the privacy rights, publicity rights, copyrights, contract rights or
    any other rights of any person or entity. We reserve the right to terminate
    the account of anyone found to be infringing on a copyright.

    You retain any and all of your rights to any Content you submit, post or
    display on or through the Service and you are responsible for protecting those
    rights. We take no responsibility and assume no liability for Content you or
    any third party posts on or through the Service. However, by posting Content
    using the Service you grant us the right and license to use, modify, perform,
    display, reproduce, and distribute such Content on and through the Service.

    Breadcrumbz has the right but not the obligation to monitor and edit all
    Content provided by users.

    In addition, Content found on or through this Service are the property of
    Breadcrumbz or used with permission. You may not distribute, modify, transmit,
    reuse, download, repost, copy, or use said Content, whether in whole or in
    part, for commercial purposes or for personal gain, without express advance
    written permission from us.

    Accounts
    --------

    When you create an account with us, you guarantee that you are above the age
    of 18, and that the information you provide us is accurate, complete, and
    current at all times. Inaccurate, incomplete, or obsolete information may
    result in the immediate termination of your account on the Service.

    You are responsible for maintaining the confidentiality of your account and
    password, including but not limited to the restriction of access to your
    computer and/or account. You agree to accept responsibility for any and all
    activities or actions that occur under your account and/or password, whether
    your password is with our Service or a third-party service. You must notify us
    immediately upon becoming aware of any breach of security or unauthorized use
    of your account.

    You may not use as a username the name of another person or entity or that is
    not lawfully available for use, a name or trademark that is subject to any
    rights of another person or entity other than you, without appropriate
    authorization. You may not use as a username any name that is offensive,
    vulgar or obscene.

    Links To Other Web Sites
    ------------------------

    Our Service may contain links to third party web sites or services that are
    not owned or controlled by Breadcrumbz

    Breadcrumbz has no control over, and assumes no responsibility for the
    content, privacy policies, or practices of any third party web sites or
    services. We do not warrant the offerings of any of these entities/individuals
    or their websites.

    You acknowledge and agree that Breadcrumbz shall not be responsible or liable,
    directly or indirectly, for any damage or loss caused or alleged to be caused
    by or in connection with use of or reliance on any such content, goods or
    services available on or through any such third party web sites or services.

    We strongly advise you to read the terms and conditions and privacy policies
    of any third party web sites or services that you visit.

    Termination
    -----------

    We may terminate or suspend your account and bar access to the Service
    immediately, without prior notice or liability, under our sole discretion, for
    any reason whatsoever and without limitation, including but not limited to a
    breach of the Terms.

    If you wish to terminate your account, you may simply discontinue using the
    Service.

    All provisions of the Terms which by their nature should survive termination
    shall survive termination, including, without limitation, ownership
    provisions, warranty disclaimers, indemnity and limitations of liability.

    Governing Law
    -------------

    These Terms shall be governed and construed in accordance with the laws of
    Utah, United States, without regard to its conflict of law provisions.

    Our failure to enforce any right or provision of these Terms will not be
    considered a waiver of those rights. If any provision of these Terms is held
    to be invalid or unenforceable by a court, the remaining provisions of these
    Terms will remain in effect. These Terms constitute the entire agreement
    between us regarding our Service, and supersede and replace any prior
    agreements we might have had between us regarding the Service.

    Changes
    -------

    We reserve the right, at our sole discretion, to modify or replace these Terms
    at any time. If a revision is material we will provide at least 30 days notice
    prior to any new terms taking effect. What constitutes a material change will
    be determined at our sole discretion.

    By continuing to access or use our Service after any revisions become
    effective, you agree to be bound by the revised terms. If you do not agree to
    the new terms, you are no longer authorized to use the Service.

    Contact Us
    ----------

    If you have any questions about these Terms, please contact us.
    """
}
